# Generated by Django 3.1.7 on 2021-06-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='slug',
        ),
        migrations.AddField(
            model_name='picturecard',
            name='pdf_linked_to',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
