# Generated by Django 3.1.2 on 2021-01-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210106_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
    ]
