# Generated by Django 3.1.2 on 2021-01-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210106_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='company.Category'),
        ),
    ]
