# Generated by Django 3.1.2 on 2021-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210107_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='testCard', to='company.Category'),
        ),
    ]
