# Generated by Django 3.1.2 on 2021-01-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210107_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='company.Category'),
        ),
    ]
