# Generated by Django 3.1.2 on 2021-01-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210107_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
