# Generated by Django 3.1.2 on 2021-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='products', to='company.Product'),
        ),
    ]
