# Generated by Django 3.1.2 on 2021-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210107_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(to='company.Product'),
        ),
    ]
