# Generated by Django 3.1.2 on 2021-01-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210107_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
