# Generated by Django 3.1.2 on 2021-01-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20210111_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
    ]
