FROM nginx:1.19.0-alpine

WORKDIR /proxy
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

RUN mkdir -p /vol/static
RUN chmod 775 /vol/static

